<a href="https://colab.research.google.com/github/swaroopgelye/Data_Science_lab_SE_A15/blob/main/Experimrnt3_Linear_Algebra_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To find the inverse of a matrix, we can use the `numpy.linalg.inv()` function. First, let's create a sample square matrix.

In [1]:
import numpy as np

# Define a sample square matrix
# Note: A matrix must be square and non-singular (determinant not zero) to have an inverse.
matrix_a = np.array([
    [4, 7],
    [2, 6]
])

print("Original Matrix A:")
print(matrix_a)

Original Matrix A:
[[4 7]
 [2 6]]


Now, let's calculate its inverse. It's a good practice to check the determinant first to ensure the inverse exists. If the determinant is zero, the matrix is singular and has no inverse.

In [2]:
# Calculate the determinant of the matrix
det_a = np.linalg.det(matrix_a)
print(f"Determinant of Matrix A: {det_a:.4f}")

if det_a == 0:
    print("This matrix is singular and does not have an inverse.")
else:
    # Calculate the inverse of the matrix
    inverse_matrix_a = np.linalg.inv(matrix_a)

    print("\nInverse of Matrix A:")
    print(inverse_matrix_a)

    # Verify the inverse: A * A_inv should be an identity matrix
    identity_check = np.dot(matrix_a, inverse_matrix_a)
    print("\nVerification (A * A_inv):")
    print(identity_check.round(4)) # Round to handle floating point inaccuracies

Determinant of Matrix A: 10.0000

Inverse of Matrix A:
[[ 0.6 -0.7]
 [-0.2  0.4]]

Verification (A * A_inv):
[[ 1. -0.]
 [ 0.  1.]]
